# Day 15

# K_Fold

K-fold cross-validation is a technique for evaluating predictive models. The dataset is divided into k subsets or folds. The model is trained and evaluated k times, using a different fold as the validation set each time. Performance metrics from each fold are averaged to estimate the model's generalization performance.

In [5]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

digits = load_digits()

In [6]:
from sklearn.model_selection import  train_test_split
x_train,x_test,y_train,y_test =  train_test_split(digits.data,digits.target,test_size=0.3)

In [7]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.975925925925926

In [8]:
svc = SVC()
svc.fit(x_train,y_train)
svc.score(x_test,y_test)

0.9925925925925926

In [9]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9888888888888889

In [10]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [11]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [12]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [13]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9925925925925926

# Day 16

## K Fold Straight

Stratified k-fold cross validation is a variation of k-fold cross validation that takes class imbalance into account when dividing data into folds for model evaluation. In stratified k-fold, the ratio between the target classes is the same in each fold as it is in the full dataset. 


In [14]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)


In [17]:
score_l = []
score_svm = []
score_rf = []
for train_index,test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index],\
                                      digits.target[train_index],digits.target[test_index]
    score_l.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    score_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test))

C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stab

In [18]:
score_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [19]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [20]:
score_rf

[0.9398998330550918, 0.9549248747913188, 0.9115191986644408]

In [21]:
from sklearn.model_selection import cross_val_score

In [22]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stab

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [23]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [24]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.94166667, 0.90555556, 0.94707521, 0.96935933, 0.90250696])