# Day 13

# Numpy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

In [1]:
import numpy as np

In [2]:
list = [1,2,3,4,5]

In [3]:
arr = np.array(list)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
type(arr)

numpy.ndarray

In [7]:
#shape function show how many row and column does a array have
arr.shape

(5,)

In [9]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,0]
list3 = [10,11,12,13,14]
arr = np.array([list1,list2,list3])

In [10]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [10, 11, 12, 13, 14]])

In [11]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [10 11 12 13 14]]


In [13]:
arr.shape

(3, 5)

In [14]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 0, 10, 11],
       [12, 13, 14]])

In [15]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [10 11 12 13 14]]


In [16]:
arr.shape

(3, 5)

# Indexing

In [17]:
array = np.array([1,2,3,4,5])

In [18]:
array[3]

4

In [19]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [10 11 12 13 14]]


In [20]:
arr[0][1]

2

In [22]:
#here first colon is used for row and second colon is used for columns
#on the left side on colon we use starting point and on the right side we write end point
# if we don't wirte anything it will print whole row and column
arr[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [10, 11, 12, 13, 14]])

In [23]:
#printing first two row
arr[0:2,:]

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [24]:
#now printing first 2 element from first 2 row
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [28]:
#arange function is used for print the value form array in a given range
#printing array from range 0 to 10 in arr
arr = np.arange(0,10)

In [29]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# if we use step argument thw it will print leaving that much values

In [31]:
arr = np.arange(0,10,step=2)

In [32]:
arr

array([0, 2, 4, 6, 8])

In [35]:
#replacing all the values in the arr array from index 3 by 100
# used for pass by reference
arr[3:]=100

In [36]:
arr

array([  0,   2,   4, 100, 100])

In [37]:
# copy array used for pass by value

In [38]:
arr1 = arr.copy()

In [39]:
print(arr)
arr1[3:]=500
print(arr1)

[  0   2   4 100 100]
[  0   2   4 500 500]


In [40]:
print(arr)

[  0   2   4 100 100]


In [41]:
arr*2

array([  0,   4,   8, 200, 200])

In [42]:
arr<100

array([ True,  True,  True, False, False])

In [43]:
arr[arr<100]

array([0, 2, 4])

In [45]:
#creating array with value 1
np.ones(4)

array([1., 1., 1., 1.])

In [46]:
#creating a randm array of given size where values ranges from 0 to 1
np.random.rand(3,4)

array([[0.7353264 , 0.90637161, 0.44111704, 0.78755907],
       [0.33668392, 0.46738028, 0.17564184, 0.09445326],
       [0.5009525 , 0.63955996, 0.32933246, 0.39912193]])